#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="2.0.9"
URL="https://github.com/yiisoft/yii2/releases/download/${VERSION}/yii-advanced-app-${VERSION}.tgz"

dl $URL /usr/local/src

