#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="$(NO_TAGS=1 gh_releases yiisoft/yii2 | tail -1)"
FILENAME="yii-advanced-app-$VERSION.tgz"
URL="https://github.com/yiisoft/yii2/releases/download/$VERSION/$FILENAME"

dl $URL /usr/local/src

