#!/bin/bash -e

set -x

VERSION=2.0.55
FILENAME="yii-advanced-app-$VERSION.tgz"
URL="https://github.com/yiisoft/yii2/releases/download/$VERSION/$FILENAME"
SHA256=e4e74986791b14deb0175685e9c45ebf0809984ae9dd19d284142fb06cbb348a
curl_args=(--fail --location --show-error)
if [[ -n ${FAB_HTTP_PROXY:-} ]]; then
    curl_args+=(--proxy "$FAB_HTTP_PROXY")
fi

curl "${curl_args[@]}" --output "/usr/local/src/$FILENAME" "$URL"
printf '%s  %s\n' "$SHA256" "/usr/local/src/$FILENAME" | sha256sum -c -
