#!/bin/bash -ex

DB_NAME=yiiframework
DB_USER=yiiframework
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
GII_PASS=turnkey

SRC=/usr/local/src
DST=/usr/local/share/yiiframework
WEBROOT=/var/www/yiiframework

# unpack and create symlink to yii cli
tar -zxf $SRC/yii-*.tar.gz -C $(dirname $DST)
mv $(dirname $DST)/yii-* $DST
rm $SRC/yii-*.tar.gz

ln -s $DST/framework/yiic /usr/local/bin/yiic

# create app, apply custom overlay and tweak
echo -e "yes\\n" | yiic webapp $WEBROOT

cp -TdR $SRC/yiiframework.overlay $WEBROOT
rm -rf $SRC/yiiframework.overlay

CONFIG=$WEBROOT/protected/config
sed -i "s|'password' =>.*|'password' => '$DB_PASS',|" $CONFIG/main.php
sed -i "s|'password' =>.*|'password' => '$DB_PASS',|" $CONFIG/console.php
sed -i "s|'password'=>.*|'password'=>'$GII_PASS',|" $CONFIG/main.php
sed -i "s|'adminEmail'=>.*|'adminEmail'=>'$ADMIN_MAIL',|" $CONFIG/main.php

CONF=$WEBROOT/protected/components/UserIdentity.php
sed -i "s|'admin'=>'admin'|'admin'=>'$ADMIN_PASS'|" $CONF

CONF=$WEBROOT/protected/views/site/login.php
sed -i "s|admin/admin|admin/$ADMIN_PASS|" $CONF

# tweak permissions
chown -R www-data:www-data $WEBROOT
chmod 640 $CONFIG/main.php
chmod 640 $CONFIG/console.php

# setup the database
/etc/init.d/mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

/etc/init.d/mysql stop

# configure apache
a2dissite default
a2ensite yiiframework
a2enmod rewrite

