#!/bin/bash -ex

#switched to Yii2 conventions
DB_NAME=yii2
DB_USER=yii2
DB_PASS=$(mcookie)

#ADMIN_NAME=admin
#ADMIN_PASS=turnkey
#ADMIN_MAIL=admin@example.com
#GII_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/yiiframework

# unpack
tar -zxf $SRC/yii-*.tgz -C $WEBROOT
rm $SRC/yii-*.tgz

cd $WEBROOT

#install Composer globally
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

php init --env=Production --overwrite=All
ln -s /var/www/yiiframework/yii /usr/local/bin/yii

CONFIG=$WEBROOT/common/config/main-local.php
sed -i "s|'dsn' =>.*|'dsn' => 'mysql:host=localhost;dbname=$DB_NAME',|" $CONFIG
sed -i "s|'username' =>.*|'username' => '$DB_USER',|" $CONFIG
sed -i "s|'password' =>.*|'password' => '$DB_PASS',|" $CONFIG

#sed -i "s|'password'=>.*|'password'=>'$GII_PASS',|" $CONFIG/main.php
#sed -i "s|'adminEmail'=>.*|'adminEmail'=>'$ADMIN_MAIL',|" $CONFIG/main.php

#CONF=$WEBROOT/protected/components/UserIdentity.php
#sed -i "s|'admin'=>'admin'|'admin'=>'$ADMIN_PASS'|" $CONF

#CONF=$WEBROOT/protected/views/site/login.php
#sed -i "s|admin/admin|admin/$ADMIN_PASS|" $CONF

# tweak permissions
chown -R www-data:www-data $WEBROOT
chmod 640 $CONFIG

# setup the database
/etc/init.d/mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

echo 'yes' | yii migrate/up

/etc/init.d/mysql stop

# configure apache
a2dissite default
a2ensite yiiframework
a2enmod rewrite

