#!/bin/bash -e
# regenerate yiiframework mysql password

. /etc/default/inithooks

CONFIG=/var/www/yiiframework/protected/config
PASSWORD=$(mcookie)

sed -i "s|'password' =>.*|'password' => '$PASSWORD',|" $CONFIG/main.php
sed -i "s|'password' =>.*|'password' => '$PASSWORD',|" $CONFIG/console.php
$INITHOOKS_PATH/bin/mysqlconf.py --user=yiiframework --pass="$PASSWORD"

